CREATE TABLE `edu_course_kpoint` (
  `kpoint_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `course_id` int(11) DEFAULT '0' COMMENT '课程id',
  `name` varchar(500) DEFAULT NULL COMMENT '节点名称',
  `parent_id` int(11) DEFAULT '0' COMMENT '父级id',
  `add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `sort` int(11) DEFAULT '0' COMMENT '显示排序',
  `play_count` int(11) DEFAULT '0' COMMENT '播放次数',
  `is_free` tinyint(1) DEFAULT '0' COMMENT '是否可以试听1免费2收费',
  `video_url` varchar(500) DEFAULT NULL COMMENT '视频地址',
  `replayUrl` varchar(500) DEFAULT NULL COMMENT '回放地址',
  `teacher_id` int(11) DEFAULT '0' COMMENT '讲师id',
  `play_time` varchar(100) DEFAULT '' COMMENT '播放时间',
  `kpoint_type` int(1) DEFAULT '0' COMMENT '节点类型 0文件目录 1视频',
  `video_type` varchar(30) DEFAULT NULL COMMENT '视频类型',
  `file_type` varchar(20) DEFAULT NULL COMMENT 'video视频 audio音频 file文档 txt文本 atlas图片集 lineCourse线下课',
  `content` longtext COMMENT '文本',
  `page_count` int(11) DEFAULT NULL COMMENT '页数',
  `live_begin_time` datetime DEFAULT NULL COMMENT '直播开始时间',
  `live_end_time` datetime DEFAULT NULL COMMENT '直播结束时间',
  `intoLiveRoom` varchar(30) DEFAULT NULL COMMENT '进入直播 （百家云讲师邀请码）',
  `supplier` varchar(30) DEFAULT '' COMMENT '直播供应商',
  `openType` varchar(10) DEFAULT NULL COMMENT '打开方式(WEB网页APP客户端)',
  `autoReplay` int(2) DEFAULT '1' COMMENT '是否自动回放1是，2否',
  `maxUsers` int(11) DEFAULT '0' COMMENT '最大人数（用于三体）',
  PRIMARY KEY (`kpoint_id`) USING BTREE,
  KEY `course_id` (`course_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=846 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='知识点的基本信息';
